[env:megaatmega2560]
platform  = atmelavr
board     = megaatmega2560
framework = arduino

; Select Timer1 (OC1A=pin11, OC1B=pin12, OC1C=pin13) for FastAccelStepper.
; Default on Mega 2560 is Timer4 (pins 6,7,8) which doesn't match our wiring.
build_flags = -DFAS_TIMER_MODULE=1

lib_deps =
    waspinator/AccelStepper @ ^1.64.0
    bogde/HX711 @ ^0.7.5
    gin66/FastAccelStepper @ ^0.30.9

monitor_speed = 115200
